-- This is an empty migration.

ALTER TABLE "Token" ADD COLUMN "month" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "tge" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m1" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m2" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m3" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m4" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m5" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m6" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m7" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m8" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m9" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m10" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m12" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m13" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m14" VARCHAR(255)[];
ALTER TABLE "Token" ADD COLUMN "m15" VARCHAR(255)[];
